export const FETCH_DATA = 'FETCH_DATA';
export const NEW_TOP_FOLDER = 'NEW_POST';
export const NEW_PROJECT = 'NEW_PROJECT';
export const NEW_SONG = 'NEW_SONG';
export const FETCH_MENU_ITEMS_WITH_CATEGORIES = 'FETCH_MENU_ITEMS_WITH_CATEGORIES'
export const FETCH_MENU_ITEMS_WITHOUT_CATEGORIES = 'FETCH_MENU_ITEMS_WITHOUT_CATEGORIES'
export const GET_META_DATA = 'GET_META_DATA'